// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/route.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyService_CreateServiceToken_FullMethodName = "/key.v1.KeyService/CreateServiceToken"
	KeyService_CreateAPIToken_FullMethodName     = "/key.v1.KeyService/CreateAPIToken"
	KeyService_CreateAPIClient_FullMethodName    = "/key.v1.KeyService/CreateAPIClient"
	KeyService_ListAPIClients_FullMethodName     = "/key.v1.KeyService/ListAPIClients"
	KeyService_GetAPIClient_FullMethodName       = "/key.v1.KeyService/GetAPIClient"
	KeyService_DeleteAPIClient_FullMethodName    = "/key.v1.KeyService/DeleteAPIClient"
	KeyService_Status_FullMethodName             = "/key.v1.KeyService/Status"
	KeyService_ListCmkKeys_FullMethodName        = "/key.v1.KeyService/ListCmkKeys"
	KeyService_CreateKey_FullMethodName          = "/key.v1.KeyService/CreateKey"
	KeyService_RotateKey_FullMethodName          = "/key.v1.KeyService/RotateKey"
	KeyService_RotateWrapKey_FullMethodName      = "/key.v1.KeyService/RotateWrapKey"
	KeyService_Encrypt_FullMethodName            = "/key.v1.KeyService/Encrypt"
	KeyService_Decrypt_FullMethodName            = "/key.v1.KeyService/Decrypt"
	KeyService_Sing_FullMethodName               = "/key.v1.KeyService/Sing"
	KeyService_Verify_FullMethodName             = "/key.v1.KeyService/Verify"
	KeyService_CreateJWT_FullMethodName          = "/key.v1.KeyService/CreateJWT"
	KeyService_VerifyJWT_FullMethodName          = "/key.v1.KeyService/VerifyJWT"
	KeyService_ReadJWT_FullMethodName            = "/key.v1.KeyService/ReadJWT"
)

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyServiceClient interface {
	CreateServiceToken(ctx context.Context, in *CreateServiceTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	CreateAPIToken(ctx context.Context, in *CreateAPITokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	CreateAPIClient(ctx context.Context, in *CreateAPIClientRequest, opts ...grpc.CallOption) (*CreateAPIClientResponse, error)
	ListAPIClients(ctx context.Context, in *ListAPIClientsRequest, opts ...grpc.CallOption) (*ListAPIClientsResponse, error)
	GetAPIClient(ctx context.Context, in *GetAPIClientRequest, opts ...grpc.CallOption) (*CreateAPIClientResponse, error)
	DeleteAPIClient(ctx context.Context, in *DeleteAPIClientRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListCmkKeys(ctx context.Context, in *ListCmkKeysRequest, opts ...grpc.CallOption) (*ListCmkKeysResponse, error)
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error)
	RotateWrapKey(ctx context.Context, in *RotateWrapKeyRequest, opts ...grpc.CallOption) (*RotateWrapKeyResponse, error)
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	Sing(ctx context.Context, in *SingRequest, opts ...grpc.CallOption) (*SingResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	CreateJWT(ctx context.Context, in *CreateJWTRequest, opts ...grpc.CallOption) (*CreateJWTResponse, error)
	VerifyJWT(ctx context.Context, in *VerifyJWTRequest, opts ...grpc.CallOption) (*VerifyJWTResponse, error)
	ReadJWT(ctx context.Context, in *ReadJWTRequest, opts ...grpc.CallOption) (*ReadJWTResponse, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) CreateServiceToken(ctx context.Context, in *CreateServiceTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, KeyService_CreateServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) CreateAPIToken(ctx context.Context, in *CreateAPITokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, KeyService_CreateAPIToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) CreateAPIClient(ctx context.Context, in *CreateAPIClientRequest, opts ...grpc.CallOption) (*CreateAPIClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIClientResponse)
	err := c.cc.Invoke(ctx, KeyService_CreateAPIClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) ListAPIClients(ctx context.Context, in *ListAPIClientsRequest, opts ...grpc.CallOption) (*ListAPIClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIClientsResponse)
	err := c.cc.Invoke(ctx, KeyService_ListAPIClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) GetAPIClient(ctx context.Context, in *GetAPIClientRequest, opts ...grpc.CallOption) (*CreateAPIClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIClientResponse)
	err := c.cc.Invoke(ctx, KeyService_GetAPIClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) DeleteAPIClient(ctx context.Context, in *DeleteAPIClientRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, KeyService_DeleteAPIClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KeyService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) ListCmkKeys(ctx context.Context, in *ListCmkKeysRequest, opts ...grpc.CallOption) (*ListCmkKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCmkKeysResponse)
	err := c.cc.Invoke(ctx, KeyService_ListCmkKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_CreateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RotateWrapKey(ctx context.Context, in *RotateWrapKeyRequest, opts ...grpc.CallOption) (*RotateWrapKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateWrapKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_RotateWrapKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, KeyService_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, KeyService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Sing(ctx context.Context, in *SingRequest, opts ...grpc.CallOption) (*SingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingResponse)
	err := c.cc.Invoke(ctx, KeyService_Sing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, KeyService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) CreateJWT(ctx context.Context, in *CreateJWTRequest, opts ...grpc.CallOption) (*CreateJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJWTResponse)
	err := c.cc.Invoke(ctx, KeyService_CreateJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) VerifyJWT(ctx context.Context, in *VerifyJWTRequest, opts ...grpc.CallOption) (*VerifyJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyJWTResponse)
	err := c.cc.Invoke(ctx, KeyService_VerifyJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) ReadJWT(ctx context.Context, in *ReadJWTRequest, opts ...grpc.CallOption) (*ReadJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadJWTResponse)
	err := c.cc.Invoke(ctx, KeyService_ReadJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility.
type KeyServiceServer interface {
	CreateServiceToken(context.Context, *CreateServiceTokenRequest) (*TokenResponse, error)
	CreateAPIToken(context.Context, *CreateAPITokenRequest) (*TokenResponse, error)
	CreateAPIClient(context.Context, *CreateAPIClientRequest) (*CreateAPIClientResponse, error)
	ListAPIClients(context.Context, *ListAPIClientsRequest) (*ListAPIClientsResponse, error)
	GetAPIClient(context.Context, *GetAPIClientRequest) (*CreateAPIClientResponse, error)
	DeleteAPIClient(context.Context, *DeleteAPIClientRequest) (*OperationStatus, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	ListCmkKeys(context.Context, *ListCmkKeysRequest) (*ListCmkKeysResponse, error)
	CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error)
	RotateWrapKey(context.Context, *RotateWrapKeyRequest) (*RotateWrapKeyResponse, error)
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	Sing(context.Context, *SingRequest) (*SingResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	CreateJWT(context.Context, *CreateJWTRequest) (*CreateJWTResponse, error)
	VerifyJWT(context.Context, *VerifyJWTRequest) (*VerifyJWTResponse, error)
	ReadJWT(context.Context, *ReadJWTRequest) (*ReadJWTResponse, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyServiceServer struct{}

func (UnimplementedKeyServiceServer) CreateServiceToken(context.Context, *CreateServiceTokenRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceToken not implemented")
}
func (UnimplementedKeyServiceServer) CreateAPIToken(context.Context, *CreateAPITokenRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIToken not implemented")
}
func (UnimplementedKeyServiceServer) CreateAPIClient(context.Context, *CreateAPIClientRequest) (*CreateAPIClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIClient not implemented")
}
func (UnimplementedKeyServiceServer) ListAPIClients(context.Context, *ListAPIClientsRequest) (*ListAPIClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAPIClients not implemented")
}
func (UnimplementedKeyServiceServer) GetAPIClient(context.Context, *GetAPIClientRequest) (*CreateAPIClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAPIClient not implemented")
}
func (UnimplementedKeyServiceServer) DeleteAPIClient(context.Context, *DeleteAPIClientRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAPIClient not implemented")
}
func (UnimplementedKeyServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedKeyServiceServer) ListCmkKeys(context.Context, *ListCmkKeysRequest) (*ListCmkKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCmkKeys not implemented")
}
func (UnimplementedKeyServiceServer) CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedKeyServiceServer) RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedKeyServiceServer) RotateWrapKey(context.Context, *RotateWrapKeyRequest) (*RotateWrapKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateWrapKey not implemented")
}
func (UnimplementedKeyServiceServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedKeyServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedKeyServiceServer) Sing(context.Context, *SingRequest) (*SingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sing not implemented")
}
func (UnimplementedKeyServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedKeyServiceServer) CreateJWT(context.Context, *CreateJWTRequest) (*CreateJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJWT not implemented")
}
func (UnimplementedKeyServiceServer) VerifyJWT(context.Context, *VerifyJWTRequest) (*VerifyJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyJWT not implemented")
}
func (UnimplementedKeyServiceServer) ReadJWT(context.Context, *ReadJWTRequest) (*ReadJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadJWT not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}
func (UnimplementedKeyServiceServer) testEmbeddedByValue()                    {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_CreateServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CreateServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CreateServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CreateServiceToken(ctx, req.(*CreateServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_CreateAPIToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPITokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CreateAPIToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CreateAPIToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CreateAPIToken(ctx, req.(*CreateAPITokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_CreateAPIClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CreateAPIClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CreateAPIClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CreateAPIClient(ctx, req.(*CreateAPIClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_ListAPIClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).ListAPIClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_ListAPIClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).ListAPIClients(ctx, req.(*ListAPIClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_GetAPIClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPIClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).GetAPIClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_GetAPIClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).GetAPIClient(ctx, req.(*GetAPIClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_DeleteAPIClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAPIClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).DeleteAPIClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_DeleteAPIClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).DeleteAPIClient(ctx, req.(*DeleteAPIClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_ListCmkKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCmkKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).ListCmkKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_ListCmkKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).ListCmkKeys(ctx, req.(*ListCmkKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RotateWrapKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateWrapKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RotateWrapKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_RotateWrapKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RotateWrapKey(ctx, req.(*RotateWrapKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Sing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Sing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Sing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Sing(ctx, req.(*SingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_CreateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).CreateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_CreateJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).CreateJWT(ctx, req.(*CreateJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_VerifyJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).VerifyJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_VerifyJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).VerifyJWT(ctx, req.(*VerifyJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_ReadJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).ReadJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_ReadJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).ReadJWT(ctx, req.(*ReadJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "key.v1.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServiceToken",
			Handler:    _KeyService_CreateServiceToken_Handler,
		},
		{
			MethodName: "CreateAPIToken",
			Handler:    _KeyService_CreateAPIToken_Handler,
		},
		{
			MethodName: "CreateAPIClient",
			Handler:    _KeyService_CreateAPIClient_Handler,
		},
		{
			MethodName: "ListAPIClients",
			Handler:    _KeyService_ListAPIClients_Handler,
		},
		{
			MethodName: "GetAPIClient",
			Handler:    _KeyService_GetAPIClient_Handler,
		},
		{
			MethodName: "DeleteAPIClient",
			Handler:    _KeyService_DeleteAPIClient_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _KeyService_Status_Handler,
		},
		{
			MethodName: "ListCmkKeys",
			Handler:    _KeyService_ListCmkKeys_Handler,
		},
		{
			MethodName: "CreateKey",
			Handler:    _KeyService_CreateKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _KeyService_RotateKey_Handler,
		},
		{
			MethodName: "RotateWrapKey",
			Handler:    _KeyService_RotateWrapKey_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _KeyService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _KeyService_Decrypt_Handler,
		},
		{
			MethodName: "Sing",
			Handler:    _KeyService_Sing_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _KeyService_Verify_Handler,
		},
		{
			MethodName: "CreateJWT",
			Handler:    _KeyService_CreateJWT_Handler,
		},
		{
			MethodName: "VerifyJWT",
			Handler:    _KeyService_VerifyJWT_Handler,
		},
		{
			MethodName: "ReadJWT",
			Handler:    _KeyService_ReadJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/route.proto",
}
