// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package views is a generated GoMock package.
package views

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountCmkCreationKeyQueueView mocks base method.
func (m *MockRepository) CountCmkCreationKeyQueueView(query string, args ...any) (uint, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountCmkCreationKeyQueueView", varargs...)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCmkCreationKeyQueueView indicates an expected call of CountCmkCreationKeyQueueView.
func (mr *MockRepositoryMockRecorder) CountCmkCreationKeyQueueView(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCmkCreationKeyQueueView", reflect.TypeOf((*MockRepository)(nil).CountCmkCreationKeyQueueView), varargs...)
}

// QueryCmkCreationKeyQueueView mocks base method.
func (m *MockRepository) QueryCmkCreationKeyQueueView(query string, args ...any) ([]CmkCreationKeyQueueView, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCmkCreationKeyQueueView", varargs...)
	ret0, _ := ret[0].([]CmkCreationKeyQueueView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCmkCreationKeyQueueView indicates an expected call of QueryCmkCreationKeyQueueView.
func (mr *MockRepositoryMockRecorder) QueryCmkCreationKeyQueueView(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCmkCreationKeyQueueView", reflect.TypeOf((*MockRepository)(nil).QueryCmkCreationKeyQueueView), varargs...)
}

// QueryCmkKeyCreationQueueView mocks base method.
func (m *MockRepository) QueryCmkKeyCreationQueueView(query string, args ...any) ([]CmkKeyCreationQueueView, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCmkKeyCreationQueueView", varargs...)
	ret0, _ := ret[0].([]CmkKeyCreationQueueView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCmkKeyCreationQueueView indicates an expected call of QueryCmkKeyCreationQueueView.
func (mr *MockRepositoryMockRecorder) QueryCmkKeyCreationQueueView(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCmkKeyCreationQueueView", reflect.TypeOf((*MockRepository)(nil).QueryCmkKeyCreationQueueView), varargs...)
}

// QueryCmkKeyVersionView mocks base method.
func (m *MockRepository) QueryCmkKeyVersionView(query string, args ...any) ([]CmkKeyVersionView, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCmkKeyVersionView", varargs...)
	ret0, _ := ret[0].([]CmkKeyVersionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCmkKeyVersionView indicates an expected call of QueryCmkKeyVersionView.
func (mr *MockRepositoryMockRecorder) QueryCmkKeyVersionView(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCmkKeyVersionView", reflect.TypeOf((*MockRepository)(nil).QueryCmkKeyVersionView), varargs...)
}

// QueryCmkKeyView mocks base method.
func (m *MockRepository) QueryCmkKeyView(query string, args ...any) ([]CmkKeyView, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCmkKeyView", varargs...)
	ret0, _ := ret[0].([]CmkKeyView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCmkKeyView indicates an expected call of QueryCmkKeyView.
func (mr *MockRepositoryMockRecorder) QueryCmkKeyView(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCmkKeyView", reflect.TypeOf((*MockRepository)(nil).QueryCmkKeyView), varargs...)
}

// QueryCmkWrappingKeyRefView mocks base method.
func (m *MockRepository) QueryCmkWrappingKeyRefView(query string, args ...any) ([]CmkWrappingKeyRefView, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryCmkWrappingKeyRefView", varargs...)
	ret0, _ := ret[0].([]CmkWrappingKeyRefView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCmkWrappingKeyRefView indicates an expected call of QueryCmkWrappingKeyRefView.
func (mr *MockRepositoryMockRecorder) QueryCmkWrappingKeyRefView(query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCmkWrappingKeyRefView", reflect.TypeOf((*MockRepository)(nil).QueryCmkWrappingKeyRefView), varargs...)
}

// ReadCmkCreationKeyQueueView mocks base method.
func (m *MockRepository) ReadCmkCreationKeyQueueView() ([]CmkCreationKeyQueueView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCmkCreationKeyQueueView")
	ret0, _ := ret[0].([]CmkCreationKeyQueueView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCmkCreationKeyQueueView indicates an expected call of ReadCmkCreationKeyQueueView.
func (mr *MockRepositoryMockRecorder) ReadCmkCreationKeyQueueView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCmkCreationKeyQueueView", reflect.TypeOf((*MockRepository)(nil).ReadCmkCreationKeyQueueView))
}

// ReadCmkKeyCreationQueueView mocks base method.
func (m *MockRepository) ReadCmkKeyCreationQueueView() ([]CmkKeyCreationQueueView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCmkKeyCreationQueueView")
	ret0, _ := ret[0].([]CmkKeyCreationQueueView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCmkKeyCreationQueueView indicates an expected call of ReadCmkKeyCreationQueueView.
func (mr *MockRepositoryMockRecorder) ReadCmkKeyCreationQueueView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCmkKeyCreationQueueView", reflect.TypeOf((*MockRepository)(nil).ReadCmkKeyCreationQueueView))
}

// ReadCmkKeyVersionView mocks base method.
func (m *MockRepository) ReadCmkKeyVersionView() ([]CmkKeyVersionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCmkKeyVersionView")
	ret0, _ := ret[0].([]CmkKeyVersionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCmkKeyVersionView indicates an expected call of ReadCmkKeyVersionView.
func (mr *MockRepositoryMockRecorder) ReadCmkKeyVersionView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCmkKeyVersionView", reflect.TypeOf((*MockRepository)(nil).ReadCmkKeyVersionView))
}

// ReadCmkKeyView mocks base method.
func (m *MockRepository) ReadCmkKeyView() ([]CmkKeyView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCmkKeyView")
	ret0, _ := ret[0].([]CmkKeyView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCmkKeyView indicates an expected call of ReadCmkKeyView.
func (mr *MockRepositoryMockRecorder) ReadCmkKeyView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCmkKeyView", reflect.TypeOf((*MockRepository)(nil).ReadCmkKeyView))
}

// ReadCmkWrappingKeyRefView mocks base method.
func (m *MockRepository) ReadCmkWrappingKeyRefView() ([]CmkWrappingKeyRefView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCmkWrappingKeyRefView")
	ret0, _ := ret[0].([]CmkWrappingKeyRefView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCmkWrappingKeyRefView indicates an expected call of ReadCmkWrappingKeyRefView.
func (mr *MockRepositoryMockRecorder) ReadCmkWrappingKeyRefView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCmkWrappingKeyRefView", reflect.TypeOf((*MockRepository)(nil).ReadCmkWrappingKeyRefView))
}
