{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.selfSignedIssuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.selfSignedIssuer.name }}
  namespace: {{ include "dragon-cmk.namespace" . }}
  labels:
    {{- include "dragon-cmk.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
{{- end }}
{{- if .Values.certManager.ca.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.ca.certificateName }}
  namespace: {{ include "dragon-cmk.namespace" . }}
  labels:
    {{- include "dragon-cmk.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ .Values.certManager.ca.commonName | quote }}
  secretName: {{ .Values.certManager.ca.secretName }}
  duration: {{ .Values.certManager.ca.duration }}
  renewBefore: {{ .Values.certManager.ca.renewBefore }}
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: {{ .Values.certManager.selfSignedIssuer.name }}
    kind: Issuer
    group: cert-manager.io
---
{{- end }}
{{- if .Values.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  namespace: {{ include "dragon-cmk.namespace" . }}
  labels:
    {{- include "dragon-cmk.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Values.certManager.ca.secretName }}
---
{{- end }}
{{- if .Values.certManager.server.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.server.certificateName }}
  namespace: {{ include "dragon-cmk.namespace" . }}
  labels:
    {{- include "dragon-cmk.labels" . | nindent 4 }}
spec:
  secretName: {{ include "dragon-cmk.tlsSecretName" . }}
  duration: {{ .Values.certManager.server.duration }}
  renewBefore: {{ .Values.certManager.server.renewBefore }}
  {{ if .Values.certManager.server.commonName }}
  commonName: {{ .Values.certManager.server.commonName | quote }}
  {{ end }}
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  dnsNames:
    {{ if .Values.certManager.server.dnsNames }}
    {{ toYaml .Values.certManager.server.dnsNames | nindent 4 }}
    {{ else }}
    - {{ include "dragon-cmk.fullname" . }}
    - {{ printf "%s.%s" (include "dragon-cmk.fullname" .) (include "dragon-cmk.namespace" .) }}
    - {{ printf "%s.%s.svc" (include "dragon-cmk.fullname" .) (include "dragon-cmk.namespace" .) }}
    - {{ printf "%s.%s.svc.cluster.local" (include "dragon-cmk.fullname" .) (include "dragon-cmk.namespace" .) }}
    {{ end }}
  {{ with .Values.certManager.server.ipAddresses }}
  ipAddresses:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: {{ .Values.certManager.issuer.kind }}
    group: {{ .Values.certManager.issuer.group }}
---
{{- end }}
{{- if .Values.certManager.client.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.client.certificateName }}
  namespace: {{ include "dragon-cmk.namespace" . }}
  labels:
    {{- include "dragon-cmk.labels" . | nindent 4 }}
spec:
  secretName: {{ include "dragon-cmk.clientTlsSecretName" . }}
  duration: {{ .Values.certManager.client.duration }}
  renewBefore: {{ .Values.certManager.client.renewBefore }}
  commonName: {{ .Values.certManager.client.commonName | quote }}
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - client auth
  {{ with .Values.certManager.client.dnsNames }}
  dnsNames:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  {{ with .Values.certManager.client.ipAddresses }}
  ipAddresses:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: {{ .Values.certManager.issuer.kind }}
    group: {{ .Values.certManager.issuer.group }}
{{- end }}
{{- end }}
