{{- if not .Values.postgresql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dragon-cmk.postgresqlSecretName" . }}
  namespace: {{ include "dragon-cmk.namespace" . }}
  labels:
    {{- include "dragon-cmk.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.existingSecretPasswordKey }}: {{ required "postgresql.password is required when postgresql.existingSecret is empty" .Values.postgresql.password | quote }}
  {{ .Values.postgresql.existingSecretAdminPasswordKey }}: {{ required "postgresql.adminPassword is required when postgresql.existingSecret is empty" .Values.postgresql.adminPassword | quote }}
  {{ if and .Values.postgresql.postgresPassword .Values.postgresql.existingSecretPostgresPasswordKey }}
  {{ .Values.postgresql.existingSecretPostgresPasswordKey }}: {{ .Values.postgresql.postgresPassword | quote }}
  {{ end }}
{{- end }}
