// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package store is a generated GoMock package.
package store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RotateKeyVersion mocks base method.
func (m *MockRepository) RotateKeyVersion(input RotateKeyVersionInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateKeyVersion", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateKeyVersion indicates an expected call of RotateKeyVersion.
func (mr *MockRepositoryMockRecorder) RotateKeyVersion(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateKeyVersion", reflect.TypeOf((*MockRepository)(nil).RotateKeyVersion), input)
}

// CreateCmkKey mocks base method.
func (m *MockRepository) CreateCmkKey(input CreateCmkKeyInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCmkKey", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCmkKey indicates an expected call of CreateCmkKey.
func (mr *MockRepositoryMockRecorder) CreateCmkKey(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCmkKey", reflect.TypeOf((*MockRepository)(nil).CreateCmkKey), input)
}

// DeleteCmkKey mocks base method.
func (m *MockRepository) DeleteCmkKey(idCmkKey uuid.UUID) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCmkKey", idCmkKey)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCmkKey indicates an expected call of DeleteCmkKey.
func (mr *MockRepositoryMockRecorder) DeleteCmkKey(idCmkKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCmkKey", reflect.TypeOf((*MockRepository)(nil).DeleteCmkKey), idCmkKey)
}

// DeleteWrappingKeyRef mocks base method.
func (m *MockRepository) DeleteWrappingKeyRef(idCmkWrappingKeyRef uuid.UUID) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWrappingKeyRef", idCmkWrappingKeyRef)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWrappingKeyRef indicates an expected call of DeleteWrappingKeyRef.
func (mr *MockRepositoryMockRecorder) DeleteWrappingKeyRef(idCmkWrappingKeyRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWrappingKeyRef", reflect.TypeOf((*MockRepository)(nil).DeleteWrappingKeyRef), idCmkWrappingKeyRef)
}

// CreateKeyCreationQueue mocks base method.
func (m *MockRepository) CreateKeyCreationQueue(input CreateKeyCreationQueueInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyCreationQueue", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyCreationQueue indicates an expected call of CreateKeyCreationQueue.
func (mr *MockRepositoryMockRecorder) CreateKeyCreationQueue(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyCreationQueue", reflect.TypeOf((*MockRepository)(nil).CreateKeyCreationQueue), input)
}

// CreateKeyVersion mocks base method.
func (m *MockRepository) CreateKeyVersion(input CreateKeyVersionInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyVersion", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyVersion indicates an expected call of CreateKeyVersion.
func (mr *MockRepositoryMockRecorder) CreateKeyVersion(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyVersion", reflect.TypeOf((*MockRepository)(nil).CreateKeyVersion), input)
}

// CreateWrappingKeyRef mocks base method.
func (m *MockRepository) CreateWrappingKeyRef(input CreateWrappingKeyRefInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWrappingKeyRef", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWrappingKeyRef indicates an expected call of CreateWrappingKeyRef.
func (mr *MockRepositoryMockRecorder) CreateWrappingKeyRef(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWrappingKeyRef", reflect.TypeOf((*MockRepository)(nil).CreateWrappingKeyRef), input)
}

// DeleteKeyCreationQueue mocks base method.
func (m *MockRepository) DeleteKeyCreationQueue(idCmkKeyCreationQueue uuid.UUID) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyCreationQueue", idCmkKeyCreationQueue)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKeyCreationQueue indicates an expected call of DeleteKeyCreationQueue.
func (mr *MockRepositoryMockRecorder) DeleteKeyCreationQueue(idCmkKeyCreationQueue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyCreationQueue", reflect.TypeOf((*MockRepository)(nil).DeleteKeyCreationQueue), idCmkKeyCreationQueue)
}

// DeleteRetiredKeyVersion mocks base method.
func (m *MockRepository) DeleteRetiredKeyVersion(idCmkKeyVersion uuid.UUID) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRetiredKeyVersion", idCmkKeyVersion)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRetiredKeyVersion indicates an expected call of DeleteRetiredKeyVersion.
func (mr *MockRepositoryMockRecorder) DeleteRetiredKeyVersion(idCmkKeyVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRetiredKeyVersion", reflect.TypeOf((*MockRepository)(nil).DeleteRetiredKeyVersion), idCmkKeyVersion)
}

// RetireKeyVersion mocks base method.
func (m *MockRepository) RetireKeyVersion(idCmkKeyVersion uuid.UUID) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetireKeyVersion", idCmkKeyVersion)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetireKeyVersion indicates an expected call of RetireKeyVersion.
func (mr *MockRepositoryMockRecorder) RetireKeyVersion(idCmkKeyVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetireKeyVersion", reflect.TypeOf((*MockRepository)(nil).RetireKeyVersion), idCmkKeyVersion)
}

// UpdateCmkKey mocks base method.
func (m *MockRepository) UpdateCmkKey(input UpdateCmkKeyInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCmkKey", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCmkKey indicates an expected call of UpdateCmkKey.
func (mr *MockRepositoryMockRecorder) UpdateCmkKey(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCmkKey", reflect.TypeOf((*MockRepository)(nil).UpdateCmkKey), input)
}

// UpdateKeyCreationQueue mocks base method.
func (m *MockRepository) UpdateKeyCreationQueue(input UpdateKeyCreationQueueInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyCreationQueue", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyCreationQueue indicates an expected call of UpdateKeyCreationQueue.
func (mr *MockRepositoryMockRecorder) UpdateKeyCreationQueue(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyCreationQueue", reflect.TypeOf((*MockRepository)(nil).UpdateKeyCreationQueue), input)
}

// UpdateKeyVersionMetadata mocks base method.
func (m *MockRepository) UpdateKeyVersionMetadata(input UpdateKeyVersionMetadataInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyVersionMetadata", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyVersionMetadata indicates an expected call of UpdateKeyVersionMetadata.
func (mr *MockRepositoryMockRecorder) UpdateKeyVersionMetadata(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyVersionMetadata", reflect.TypeOf((*MockRepository)(nil).UpdateKeyVersionMetadata), input)
}

// UpdateKeyVersionStatus mocks base method.
func (m *MockRepository) UpdateKeyVersionStatus(input UpdateKeyVersionStatusInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyVersionStatus", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyVersionStatus indicates an expected call of UpdateKeyVersionStatus.
func (mr *MockRepositoryMockRecorder) UpdateKeyVersionStatus(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyVersionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateKeyVersionStatus), input)
}

// UpdateWrappingKeyRef mocks base method.
func (m *MockRepository) UpdateWrappingKeyRef(input UpdateWrappingKeyRefInput) (*pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWrappingKeyRef", input)
	ret0, _ := ret[0].(*pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWrappingKeyRef indicates an expected call of UpdateWrappingKeyRef.
func (mr *MockRepositoryMockRecorder) UpdateWrappingKeyRef(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWrappingKeyRef", reflect.TypeOf((*MockRepository)(nil).UpdateWrappingKeyRef), input)
}
