app:
  name: dragon-cmk
  version: 0.0.1

server:
  gin:
    groups:
      - /api
      - /api/auth/v1
      - /api/keys/v1
      - /api/config/v1
    port: ":8080"
    mode: release
    UseH2C: true
    rate:
      limit: 1000
      burst: 2000
    LoggerWithConfig:
      enabled: true
      SkipPaths:
        - /health
    tls:
      enable: false
      certFile: ./certs/server/cert.pem
      keyFile: ./certs/server/key.pem
      version: tlsv12
    mtls:
      enable: false
      clientCAFile: ./certs/server/ca.pem
      clientAuth: require_and_verify_client_cert
  grpc:
    port: ":50051"
    tls:
      enable: false
      certFile: ./certs/server/cert.pem
      keyFile: ./certs/server/key.pem
      version: tlsv12
    mtls:
      enable: false
      clientCAFile: ./certs/server/ca.pem
      keyFile: require_and_verify_client_cert

logger:
  dir: logs
  level: info
  ignoredHeaders:
    - Cookies
    - Authorization
    - X-API-Key
  formatter: json
  formatDate: "2006-01-02T15:04:05.000"
  rotate:
    enable: true
    maxSize: 10
    maxBackups: 5
    maxAge: 30
    compress: true

traces:
  SkipPaths:
    - /health

jwt:
  enable: true
  transport: header
  algorithm: EDDSA
  eddsa:
    private_key: ./certs/jwt/key.pem
    public_key: ./certs/jwt/public.pem
